config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get    '/signup',  to: 'users#signup'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users	
  
  resources :article_attachments
  
  resources :articles do
    resources :comments
  end  
  root to: 'articles#index'
end

app/models/article_attachment.rb
class ArticleAttachment < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :article
end

app/controllers/article_attachments_controller.rb
class ArticleAttachmentsController < ApplicationController
  before_action :set_article_attachment, only: [:show, :edit, :update, :destroy]

  # GET /article_attachments
  # GET /article_attachments.json
  def index
    @article_attachments = ArticleAttachment.all
  end

  # GET /article_attachments/1
  # GET /article_attachments/1.json
  def show
  end

  # GET /article_attachments/new
  def new
    @article_attachment = ArticleAttachment.new
  end

  # GET /article_attachments/1/edit
  def edit
  end

  # POST /article_attachments
  # POST /article_attachments.json
  def create
    @article_attachment = ArticleAttachment.new(article_attachment_params)

    respond_to do |format|
      if @article_attachment.save
        format.html { redirect_to @article_attachment, notice: 'Article attachment was successfully created.' }
        format.json { render :show, status: :created, location: @article_attachment }
      else
        format.html { render :new }
        format.json { render json: @article_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /article_attachments/1
  # PATCH/PUT /article_attachments/1.json
  def update
    respond_to do |format|
      if @article_attachment.update(article_attachment_params)
        format.html { redirect_to @article_attachment, notice: 'Article attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @article_attachment }
      else
        format.html { render :edit }
        format.json { render json: @article_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /article_attachments/1
  # DELETE /article_attachments/1.json
  def destroy
    @article_attachment.destroy
    respond_to do |format|
      format.html { redirect_to article_attachments_url, notice: 'Article attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article_attachment
      @article_attachment = ArticleAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_attachment_params
      params.require(:article_attachment).permit(:article_id, :avatar)
    end
end

app/helpers/article_attachments_helper.rb
module ArticleAttachmentsHelper
end

app/views/article_attachments/_form.html.erb
<%= form_with(model: article_attachment, local: true) do |form| %>
  <% if article_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article_attachment.errors.count, "error") %> prohibited this article_attachment from being saved:</h2>

      <ul>
      <% article_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :article_id %>
    <%= form.number_field :article_id, id: :article_attachment_article_id %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.text_field :avatar, id: :article_attachment_avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/article_attachments/edit.html.erb
<h1>Editing Article Attachment</h1>

<%= render 'form', article_attachment: @article_attachment %>

<%= link_to 'Show', @article_attachment %> |
<%= link_to 'Back', article_attachments_path %>

app/views/article_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Article Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @article_attachments.each do |article_attachment| %>
      <tr>
        <td><%= article_attachment.article_id %></td>
        <td><%= article_attachment.avatar %></td>
        <td><%= link_to 'Show', article_attachment %></td>
        <td><%= link_to 'Edit', edit_article_attachment_path(article_attachment) %></td>
        <td><%= link_to 'Destroy', article_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article Attachment', new_article_attachment_path %>

app/views/article_attachments/new.html.erb
<h1>New Article Attachment</h1>

<%= render 'form', article_attachment: @article_attachment %>

<%= link_to 'Back', article_attachments_path %>

app/views/article_attachments/show.html.erb
<p>
  <strong>Article:</strong>
  <%= @article_attachment.article_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @article_attachment.avatar %>
</p>

<%= link_to 'Edit', edit_article_attachment_path(@article_attachment) %> |
<%= link_to 'Back', article_attachments_path %>